name: Build petclinic rest using reusable component workflow run
on:
  workflow_dispatch:
  push:
    paths:
    - ".github/workflows/master_poc-petclinic-rest.yml" 
    branches:
    - develop
    
env:
  AZURE_WEBAPP_NAME: poc-petclinic-rest1
  AZURE_WEBAPP_SLOT: production
   
jobs:
  build:
    runs-on: [latest]
    steps: 
    - uses: actions/checkout@v2
      
    - name: Running reusable build backend composite action 
      uses:  ./.github/actions/build
      with:
        APP_MODULE: "poc-petclinic-rest1"
        JAVA_VERSION: "11"
        ARTIFACT_NAME: "app"
        
  deploy:
    name: "Deploy Backend 🚀"  
    runs-on: [latest]
    needs: [build]      
    steps:
      - uses: actions/checkout@v2      
      - name: Azure Login     
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
     
      - name: Running reusable deploy backend composite action
        uses:  ./.github/actions/deploy
        with:
          ARTIFACT_NAME: "app"
          AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}  
          AZURE_WEBAPP_SLOT: ${{ env.AZURE_WEBAPP_SLOT }}
          AZURE_WEBAPP_PACKAGE_PATH: ${{github.workspace }}
